#!/bin/bash
#SBATCH -J movies_scrape
#SBATCH -n 1
#SBATCH -t 2:00:00
#SBATCH -a 1-27%5

cd $SLURM_SUBMIT_DIR
website="$(awk NR==$SLURM_ARRAY_TASK_ID url.txt)"
echo "$website"
source venv/bin/activate
python final_movie_scraper.py "$website" "$website".txt

